apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: npd-node-replace-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: npd-node-replace-clusterrole
subjects:
- kind: ServiceAccount
  name: npd-node-replace-sa
  namespace: kube-system
