apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws-cn:iam::073070604328:role/zhxingcm-npd-node-replace-iam-role
  creationTimestamp: null
  name: npd-node-replace-sa
  namespace: kube-system