apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: npd-node-replace
  name: npd-node-replace
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npd-node-replace
  strategy: {}
  template:
    metadata:
      labels:
        app: npd-node-replace
    spec:
      serviceAccount: npd-node-replace-sa
      containers:
      - image: <image_url>
        name: npd-node-replace
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: "/app/tolerance.json"
          subPath: "tolerance.json"
          readOnly: true
        env:
        - name: SELF_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SELF_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SELF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SNS_TOPIC_ARN
          value: <amazon sns topic arn>
      volumes:
      - name: config-volume
        configMap:
          name: tolerance-config