apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: npd-node-replace
  name: npd-node-replace
  namespace: fargatenamespace1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npd-node-replace
  strategy: {}
  template:
    metadata:
      labels:
        app: npd-node-replace
    spec:
      serviceAccount: npd-node-replace-sa
      containers:
      - image: zxxxx/npd-node-replace:v1.2
        name: npd-node-replace
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: "/app/tolerance.json"
          subPath: "tolerance.json"
          readOnly: true
        env:
        - name: SELF_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SELF_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SELF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SNS_TOPIC_ARN
          value: <SNS topic arn>
        - name: NODE_DOULBE_CHECK_GRACE_TIME
          value: "5"   # the grace time for double check before replacing node, in minutes, default is 3 minutes, make sure it is larger than node reboot time 
      volumes:
      - name: config-volume
        configMap:
          name: tolerance-config
