apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-08-28T07:04:30Z"
  generateName: echoserver-64cc7cc7fc-
  labels:
    app: echoserver1
    pod-template-hash: 64cc7cc7fc
  name: echoserver-64cc7cc7fc-gmj8q
  namespace: echoserver
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: echoserver-64cc7cc7fc
    uid: ae86db45-e155-45eb-b40d-59a8c927cad8
  resourceVersion: "169167930"
  uid: e5f24056-73cd-4d31-8fca-1e0a9093bc3b
spec:
  containers:
  - env:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    - name: AWS_DEFAULT_REGION
      value: cn-north-1
    - name: AWS_REGION
      value: cn-north-1
    - name: AWS_CONTAINER_CREDENTIALS_FULL_URI
      value: http://169.254.170.23/v1/credentials
    - name: AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
      value: /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
    image: public.ecr.aws/j5h7p3f5/public.echoserver:latest
    imagePullPolicy: Always
    name: echoserver
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-c2h7x
      readOnly: true
    - mountPath: /var/run/secrets/pods.eks.amazonaws.com/serviceaccount
      name: eks-pod-identity-token
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-172-31-40-203.cn-north-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app: echoserver
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
  volumes:
  - name: eks-pod-identity-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: pods.eks.amazonaws.com
          expirationSeconds: 84595
          path: eks-pod-identity-token
  - name: kube-api-access-c2h7x
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-28T07:04:43Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-28T07:04:30Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-28T07:04:43Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-28T07:04:43Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-28T07:04:30Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a0f47066153e6fdfd45ed57b3bd9b0a254b3eae5fc92fb930b7706f828e975a1
    image: public.ecr.aws/j5h7p3f5/public.echoserver:latest
    imageID: public.ecr.aws/j5h7p3f5/public.echoserver@sha256:5f48bd2f7b70aa575ca6a5b7dbb675ff5f109eb8ed4fc91fd3dbeee739e630c2
    lastState: {}
    name: echoserver
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-28T07:04:42Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-c2h7x
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/run/secrets/pods.eks.amazonaws.com/serviceaccount
      name: eks-pod-identity-token
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.31.40.203
  hostIPs:
  - ip: 172.31.40.203
  phase: Running
  podIP: 172.31.35.97
  podIPs:
  - ip: 172.31.35.97
  qosClass: BestEffort
  startTime: "2025-08-28T07:04:30Z"