apiVersion: v1
kind: ConfigMap
metadata:
  name: tolerance-config
  namespace: kube-system
data:
  tolerance.json: |
    {
      "tolerancecollection": {
        "OOMKilling": {
          "times": 2,
          "action": "reboot"
        },
        "KernelOops": {
          "times": 3,
          "action": "replace"
        }
      }
    }