apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "npd-node-replace.fullname" . }}-clusterrolebinding
  labels:
  {{- include "npd-node-replace.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "npd-node-replace.fullname" . }}-clusterrole'
subjects:
- kind: ServiceAccount
  name: '{{ include "npd-node-replace.fullname" . }}-sa'
  namespace: '{{ .Release.Namespace }}'
