apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "npd-node-replace.fullname" . }}-tolerance-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "npd-node-replace.labels" . | nindent 4 }}
data:
  tolerance.json: {{ .Values.toleranceConfig.toleranceJson | toYaml | indent 1 }}
